export const companyConfig = {
  brand: "EVER FLAME LOGISTICS",
  legalNameEn: "Shenzhen Ever Flame International Logistics Co., Ltd.",
  legalNameZh: "深圳市恒长明国际货运代理有限公司",
  contact: {
    email: null,
    phone: null,
    whatsapp: null,
    wechat: null,
  },
};

export const pagePaths = {
  home: "",
  services: "air-freight",
  india: "india-air-freight",
  malaysia: "malaysia-air-freight",
  cargo: "cargo-capabilities",
  about: "about",
  contact: "contact",
  privacy: "privacy",
};

export const airportGroups = {
  india: [
    { code: "DEL", city: { en: "Delhi", zh: "德里" } },
    { code: "BOM", city: { en: "Mumbai", zh: "孟买" } },
    { code: "MAA", city: { en: "Chennai", zh: "金奈" } },
    { code: "BLR", city: { en: "Bengaluru", zh: "班加罗尔" } },
    { code: "HYD", city: { en: "Hyderabad", zh: "海得拉巴" } },
    { code: "CCU", city: { en: "Kolkata", zh: "加尔各答" } },
  ],
  malaysia: [
    { code: "KUL", city: { en: "Kuala Lumpur", zh: "吉隆坡" } },
    { code: "PEN", city: { en: "Penang", zh: "槟城" } },
  ],
};

const sharedEn = {
  brand: companyConfig.brand,
  nav: {
    services: "Services",
    destinations: "Destinations",
    cargo: "Cargo",
    about: "About",
    contact: "Contact",
    india: "India Air Freight",
    malaysia: "Malaysia Air Freight",
    airFreight: "Air Freight Services",
    capabilities: "Cargo Capabilities",
    language: "中文",
    menu: "Menu",
    close: "Close",
  },
  common: {
    primaryCta: "Talk to an Air Freight Specialist",
    secondaryCta: "Explore Our Services",
    learnMore: "Learn more",
    routeFocus: "Route focus",
    china: "China",
    india: "India",
    malaysia: "Malaysia",
    availability: "Service availability is confirmed against the cargo, airline, documents, and destination requirements.",
    demo: "Prototype only — this form does not send or store data.",
    footerNote: "Air freight forwarding support from China to India, Malaysia, and selected South & Southeast Asian destinations.",
    privacy: "Privacy",
  },
};

const sharedZh = {
  brand: companyConfig.brand,
  nav: {
    services: "服务",
    destinations: "目的地",
    cargo: "货物能力",
    about: "关于我们",
    contact: "联系我们",
    india: "印度空运",
    malaysia: "马来西亚空运",
    airFreight: "空运服务",
    capabilities: "货物能力",
    language: "EN",
    menu: "菜单",
    close: "关闭",
  },
  common: {
    primaryCta: "联系空运顾问",
    secondaryCta: "了解我们的服务",
    learnMore: "了解更多",
    routeFocus: "重点航线",
    china: "中国",
    india: "印度",
    malaysia: "马来西亚",
    availability: "具体服务须结合货物、航空公司、文件和目的地要求确认。",
    demo: "仅为原型演示——表单不会发送或保存数据。",
    footerNote: "为中国出口至印度、马来西亚及部分南亚和东南亚目的地提供空运货代支持。",
    privacy: "隐私政策",
  },
};

export const content = {
  en: {
    ...sharedEn,
    seo: {
      home: ["Air Freight from China | EVER FLAME LOGISTICS", "Air freight forwarding support from China to India, Malaysia, and selected South & Southeast Asian destinations."],
      services: ["Air Freight Services | EVER FLAME LOGISTICS", "Airport-to-airport and door-to-door air freight forwarding support from China."],
      india: ["China to India Air Freight | EVER FLAME LOGISTICS", "Air freight forwarding support from China to DEL, BOM, MAA, BLR, HYD, and CCU."],
      malaysia: ["China to Malaysia Air Freight | EVER FLAME LOGISTICS", "Air freight forwarding support from China to KUL and PEN."],
      cargo: ["Cargo Capabilities | EVER FLAME LOGISTICS", "General cargo and eligible battery shipment handling, subject to airline and document requirements."],
      about: ["About EVER FLAME LOGISTICS", "Meet Shenzhen Ever Flame International Logistics Co., Ltd. and our air freight service approach."],
      contact: ["Contact EVER FLAME LOGISTICS", "Share your China export air freight requirements with our team."],
      privacy: ["Privacy | EVER FLAME LOGISTICS", "Privacy information for the EVER FLAME LOGISTICS website prototype."],
    },
    home: {
      eyebrow: "CHINA TO INDIA & MALAYSIA",
      title: "Air Freight from China to South & Southeast Asia",
      intro: "Airport-to-airport and door-to-door solutions for general cargo and eligible battery shipments.",
      statement: "Focused air freight support for shipments from China to India and Malaysia.",
      airportLabel: "Key destination airports",
      serviceOne: {
        number: "01",
        title: "Airport-to-Airport",
        body: "Coordinated air freight between major airports, from export handling in China through destination-airport support.",
      },
      serviceTwo: {
        number: "02",
        title: "Door-to-Door",
        body: "Pickup, export handling, air freight, destination coordination, and final delivery arranged as one service chain.",
      },
      stepsTitle: "A clear service chain",
      steps: ["Collect", "Export", "Fly", "Deliver"],
      cargoTitle: "Cargo Capability",
      cargoBody: "We support general cargo and eligible battery or battery-powered products, subject to cargo details, documents, airline rules, and route acceptance.",
      ctaTitle: "Ready to discuss your cargo?",
      ctaBody: "Tell us the origin, destination, cargo details, and preferred service mode.",
    },
    services: {
      eyebrow: "AIR FREIGHT SERVICES",
      title: "Two service modes, one coordinated journey",
      intro: "Choose airport-to-airport or door-to-door support according to how much of the shipment journey you want us to coordinate.",
      modeLabel: "Choose a service mode",
      modes: {
        airport: {
          label: "Airport-to-Airport",
          title: "From departure airport to destination airport",
          body: "Suitable when your team or consignee manages local pickup and final clearance or delivery. We coordinate export handling and the air freight movement between agreed airports.",
          points: ["Export-side cargo coordination", "Airline and routing coordination", "Origin handling and departure support", "Destination-airport handover coordination"],
        },
        door: {
          label: "Door-to-Door",
          title: "A broader end-to-end service chain",
          body: "Suitable when you want one logistics contact to coordinate pickup in China through to delivery at the agreed destination address.",
          points: ["Pickup and origin transport", "Warehouse and export handling", "Air freight and destination coordination", "Clearance support and final delivery arrangement"],
        },
      },
      chainTitle: "Service chain",
      chain: [
        ["Pickup", "Collection from the agreed origin in China."],
        ["Warehouse", "Receiving, consolidation, and handover preparation when required."],
        ["Export customs", "Export declaration coordination based on provided documents."],
        ["Air freight", "Routing and capacity coordination with suitable airline options."],
        ["Destination", "Overseas-agent coordination for arrival and local requirements."],
        ["Delivery", "Final delivery arrangement when door-to-door service is selected."],
      ],
      noteTitle: "Scope is confirmed shipment by shipment",
      noteBody: "Routing, schedule, capacity, cargo acceptance, customs requirements, and destination services vary. We confirm the practical scope after reviewing the shipment details.",
    },
    india: {
      eyebrow: "CHINA TO INDIA",
      title: "Air freight support for key Indian gateways",
      intro: "Export coordination from major airports in China to six key destination airports in India, with airport-to-airport and door-to-door options.",
      airportsTitle: "Key destination airports",
      serviceTitle: "How we support India-bound cargo",
      serviceBody: "We coordinate origin handling in China and work with destination agents for arrival support, local requirements, and delivery arrangements where available.",
      items: [
        ["Origin coordination", "Pickup, warehouse receiving, export documents, and departure handling can be arranged according to the selected scope."],
        ["Air freight planning", "Routing and capacity are reviewed against the cargo, schedule, airline requirements, and destination airport."],
        ["Destination coordination", "Local handling, clearance support, and delivery are confirmed with the destination agent for each shipment."],
      ],
      noteTitle: "No fixed transit-time promise",
      noteBody: "Schedules and transit times depend on routing, capacity, cargo acceptance, documents, customs, and local delivery conditions. Ask us to confirm the current option for your shipment.",
    },
    malaysia: {
      eyebrow: "CHINA TO MALAYSIA",
      title: "Air freight support for Kuala Lumpur and Penang",
      intro: "Airport-to-airport and door-to-door coordination from China to Malaysia, focused on KUL and PEN.",
      airportsTitle: "Key destination airports",
      serviceTitle: "A practical China–Malaysia service chain",
      serviceBody: "We align export handling, air freight, destination coordination, and optional local delivery around the cargo and consignee requirements.",
      items: [
        ["China export handling", "Pickup, warehouse receiving, export customs coordination, and departure handover as required."],
        ["KUL and PEN routing", "Routing is reviewed according to current capacity, cargo type, documents, and the preferred destination airport."],
        ["Arrival and delivery", "Destination handling and delivery scope are confirmed with local resources before shipment acceptance."],
      ],
      noteTitle: "Service details require confirmation",
      noteBody: "Availability, schedules, acceptance, documentation, and local delivery differ by shipment. We provide a current plan after reviewing the cargo information.",
    },
    cargo: {
      eyebrow: "CARGO CAPABILITY",
      title: "Clear handling expectations before cargo moves",
      intro: "We support general cargo and selected battery or battery-powered products. Acceptance is always confirmed against the exact cargo and route.",
      accordionLabel: "Cargo categories",
      categories: [
        {
          id: "general",
          title: "General cargo",
          summary: "Common commercial goods that do not require dangerous-goods handling.",
          body: "We review dimensions, weight, packaging, commodity description, export documents, and destination requirements before confirming the service plan.",
          checks: ["Accurate commodity description", "Stable packaging suitable for air transport", "Dimensions and gross/chargeable weight", "Commercial and export documentation"],
        },
        {
          id: "battery",
          title: "Batteries and battery-powered products",
          summary: "Eligible shipments may be supported after detailed compliance review.",
          body: "Acceptance depends on battery chemistry, configuration, watt-hour rating or lithium content, packing method, test documentation, labels, airline policy, route, and destination rules.",
          checks: ["Product and battery specification", "Applicable test summary and supporting documents", "Compliant packaging and markings", "Airline and route acceptance confirmed before shipment"],
        },
      ],
      warningTitle: "Confirmation is required",
      warningBody: "Do not treat this page as cargo acceptance. Send the product specification, battery information, packaging details, documents, origin, and destination for a shipment-specific review.",
    },
    about: {
      eyebrow: "ABOUT US",
      title: "A Shenzhen air freight team with destination coordination",
      intro: "Shenzhen Ever Flame International Logistics Co., Ltd. focuses on air freight forwarding from China, with India and Malaysia as key markets.",
      storyTitle: "What we do",
      storyBody: "We help exporters and importers understand the practical steps between cargo pickup in China and handover or delivery at destination. Our role is to coordinate the service chain, surface requirements early, and keep the shipment scope clear.",
      modelTitle: "How we operate",
      modelItems: [
        ["Shenzhen team", "Origin coordination, cargo review, export handling, and communication from China."],
        ["Overseas agents", "Destination handling and local delivery resources are coordinated shipment by shipment."],
        ["Clear scope", "We confirm what is included, what documents are needed, and what remains subject to airline or local approval."],
      ],
      principlesTitle: "Our working principles",
      principles: ["Keep business claims factual", "Confirm cargo requirements early", "Use one clear contact path", "Coordinate origin and destination details"],
    },
    contact: {
      eyebrow: "CONTACT",
      title: "Tell us what needs to move",
      intro: "Share the route, cargo, and preferred service mode. This prototype demonstrates the enquiry flow but does not transmit or store your information.",
      channelTitle: "Direct contact channels",
      channelUnavailable: "Verified WhatsApp, email, phone, and address details have not been added yet. External contact buttons remain hidden until real company information is provided.",
      formTitle: "Shipment enquiry",
      fields: {
        name: ["Name", "Your name"],
        company: ["Company", "Company name (optional)"],
        email: ["Email", "name@company.com"],
        contact: ["WeChat or WhatsApp", "ID or number (optional)"],
        origin: ["Origin", "City or airport in China"],
        destination: ["Destination", "City or airport"],
        message: ["Cargo and message", "Commodity, pieces, weight, dimensions, service mode, and timing"],
      },
      required: "Required",
      invalidEmail: "Enter a valid email address.",
      invalidContact: "Enter at least 5 valid characters using letters, numbers, spaces, +, -, _, or @.",
      submit: "Send demo enquiry",
      submitting: "Checking enquiry…",
      successTitle: "Demo enquiry complete",
      successBody: "Nothing was sent or saved. In production, this state will appear only after a secure form service confirms delivery.",
      another: "Start another enquiry",
    },
    privacyPage: {
      eyebrow: "PRIVACY",
      title: "Privacy information for this prototype",
      intro: "This local demonstration does not send, retain, or share form entries.",
      sections: [
        ["Prototype data handling", "The contact form validates information only in your browser. Submitted values are discarded when the success state appears or the page is refreshed."],
        ["Production requirement", "Before launch, the company must select a secure form provider, define retention and access rules, publish verified contact and legal details, and obtain any consent required by applicable law."],
        ["External services", "This prototype does not include analytics, advertising trackers, chat widgets, maps, social pixels, or third-party logistics integrations."],
      ],
    },
  },
  zh: {
    ...sharedZh,
    seo: {
      home: ["中国出口空运｜EVER FLAME LOGISTICS", "为中国出口至印度、马来西亚及部分南亚和东南亚目的地提供空运货代支持。"],
      services: ["空运服务｜EVER FLAME LOGISTICS", "提供机场到机场和门到门两种中国出口空运货代服务。"],
      india: ["中国至印度空运｜EVER FLAME LOGISTICS", "支持中国出口至 DEL、BOM、MAA、BLR、HYD 和 CCU 的空运协调。"],
      malaysia: ["中国至马来西亚空运｜EVER FLAME LOGISTICS", "支持中国出口至 KUL 和 PEN 的空运协调。"],
      cargo: ["货物能力｜EVER FLAME LOGISTICS", "支持普货及符合条件的电池和带电产品，须按航空公司及文件要求确认。"],
      about: ["关于 EVER FLAME LOGISTICS", "了解深圳市恒长明国际货运代理有限公司的空运服务方式。"],
      contact: ["联系 EVER FLAME LOGISTICS", "提交中国出口空运需求。"],
      privacy: ["隐私政策｜EVER FLAME LOGISTICS", "EVER FLAME LOGISTICS 网站原型的隐私说明。"],
    },
    home: {
      eyebrow: "中国至印度与马来西亚",
      title: "中国出口至南亚与东南亚的空运服务",
      intro: "提供机场到机场和门到门服务，支持普货及符合条件的电池和带电产品。",
      statement: "聚焦中国出口至印度和马来西亚的空运货代支持。",
      airportLabel: "主要目的地机场",
      serviceOne: {
        number: "01",
        title: "机场到机场",
        body: "协调中国出口操作与国际空运，并衔接目的地机场的到港支持。",
      },
      serviceTwo: {
        number: "02",
        title: "门到门",
        body: "可统一协调中国提货、出口操作、国际空运、目的地衔接及末端派送。",
      },
      stepsTitle: "清晰的服务链",
      steps: ["提货", "出口", "空运", "派送"],
      cargoTitle: "货物能力",
      cargoBody: "支持普货及符合条件的电池或带电产品，具体须结合货物资料、文件、航空公司规则和航线要求确认。",
      ctaTitle: "准备沟通您的货物？",
      ctaBody: "请提供起运地、目的地、货物信息和希望采用的服务方式。",
    },
    services: {
      eyebrow: "空运服务",
      title: "两种服务方式，一条协同链路",
      intro: "您可以根据希望我们协调的运输范围，选择机场到机场或门到门服务。",
      modeLabel: "选择服务方式",
      modes: {
        airport: {
          label: "机场到机场",
          title: "从起飞机场到目的地机场",
          body: "适合由发货人或收货人自行安排当地提货、清关或末端派送的货物。我们协调中国出口操作及约定机场之间的国际空运。",
          points: ["中国出口端货物协调", "航空公司与航线协调", "始发操作与出港支持", "目的地机场交接协调"],
        },
        door: {
          label: "门到门",
          title: "覆盖更完整的端到端服务链",
          body: "适合希望由一个物流联系人协调从中国提货到约定目的地地址派送的客户。",
          points: ["提货与国内运输", "仓储和出口操作", "国际空运与目的地衔接", "清关支持和末端派送安排"],
        },
      },
      chainTitle: "服务链说明",
      chain: [
        ["提货", "从中国约定地点提取货物。"],
        ["仓储", "按需要安排收货、集货和交接准备。"],
        ["出口报关", "根据客户提供的文件协调出口申报。"],
        ["国际空运", "结合货物要求协调合适的航线与运力。"],
        ["目的地衔接", "通过海外代理协调到港和当地操作要求。"],
        ["末端派送", "选择门到门服务时安排约定范围内的派送。"],
      ],
      noteTitle: "服务范围按票确认",
      noteBody: "航线、班期、运力、货物接收、清关要求和目的地服务均可能变化。我们会在审核货物资料后确认实际服务范围。",
    },
    india: {
      eyebrow: "中国至印度",
      title: "覆盖印度主要门户机场的空运支持",
      intro: "协调中国主要机场出口至印度六个重点目的地机场，提供机场到机场及门到门两种选择。",
      airportsTitle: "主要目的地机场",
      serviceTitle: "如何支持印度方向货物",
      serviceBody: "我们协调中国始发端操作，并通过目的地代理衔接到港、当地要求和可用的派送服务。",
      items: [
        ["始发端协调", "可根据服务范围安排提货、仓库收货、出口文件和出港操作。"],
        ["空运方案", "结合货物、班期、航空公司要求和目的地机场审核航线与运力。"],
        ["目的地协调", "每票货物均需与当地代理确认到港操作、清关支持和派送范围。"],
      ],
      noteTitle: "不承诺固定时效",
      noteBody: "班期和运输时效会受到航线、运力、货物接收、文件、海关及当地派送条件影响。请联系我们确认当前可行方案。",
    },
    malaysia: {
      eyebrow: "中国至马来西亚",
      title: "吉隆坡与槟城方向空运支持",
      intro: "提供中国出口至马来西亚 KUL 和 PEN 的机场到机场及门到门协调。",
      airportsTitle: "主要目的地机场",
      serviceTitle: "务实的中马空运服务链",
      serviceBody: "围绕货物和收货人要求，协调出口操作、国际空运、目的地衔接及可选的当地派送。",
      items: [
        ["中国出口操作", "按需要安排提货、仓库收货、出口报关协调和出港交接。"],
        ["KUL 与 PEN 航线", "根据当前运力、货物类型、文件和目的地机场审核航线。"],
        ["到港与派送", "货物接收前会与当地资源确认目的地操作及派送范围。"],
      ],
      noteTitle: "服务细节须确认",
      noteBody: "可用性、班期、货物接收、文件和当地派送会随每票货物变化。审核货物资料后，我们会提供当前方案。",
    },
    cargo: {
      eyebrow: "货物能力",
      title: "货物起运前先明确操作要求",
      intro: "支持普货及部分电池或带电产品，最终是否接收须结合具体货物与航线确认。",
      accordionLabel: "货物类别",
      categories: [
        {
          id: "general",
          title: "普货",
          summary: "不需要危险品操作的常见商业货物。",
          body: "确认方案前，我们会审核尺寸、重量、包装、品名、出口文件及目的地要求。",
          checks: ["准确、完整的货物品名", "适合航空运输的稳固包装", "尺寸、毛重和计费重量", "商业与出口相关文件"],
        },
        {
          id: "battery",
          title: "电池及带电产品",
          summary: "符合条件的货物可在详细合规审核后提供支持。",
          body: "是否接收取决于电池化学体系、配置、瓦时数或锂含量、包装方式、测试文件、标签、航空公司政策、航线和目的地规则。",
          checks: ["产品与电池规格", "适用的测试概要及支持文件", "合规包装与标记", "起运前确认航空公司与航线可接收"],
        },
      ],
      warningTitle: "必须提前确认",
      warningBody: "本页面不构成货物接收承诺。请提供产品规格、电池信息、包装、文件、起运地和目的地，以便按票审核。",
    },
    about: {
      eyebrow: "关于我们",
      title: "立足深圳，协调目的地资源的空运团队",
      intro: "深圳市恒长明国际货运代理有限公司专注于中国出口空运货代，印度和马来西亚是重点市场。",
      storyTitle: "我们做什么",
      storyBody: "我们帮助出口商和进口商梳理从中国提货到目的地交接或派送之间的实际步骤，协调服务链、尽早明确要求，并保持服务范围清楚透明。",
      modelTitle: "我们的运作方式",
      modelItems: [
        ["深圳团队", "负责中国始发端协调、货物审核、出口操作和沟通。"],
        ["海外代理", "按票协调目的地操作和当地派送资源。"],
        ["范围清晰", "明确包含内容、所需文件及仍须航空公司或当地确认的事项。"],
      ],
      principlesTitle: "工作原则",
      principles: ["保持业务表述真实", "尽早确认货物要求", "提供清晰联系路径", "衔接始发地与目的地细节"],
    },
    contact: {
      eyebrow: "联系我们",
      title: "请告诉我们需要运输什么",
      intro: "请提供航线、货物及希望采用的服务方式。此原型仅演示询价流程，不会传输或保存信息。",
      channelTitle: "直接联系渠道",
      channelUnavailable: "尚未添加已核实的微信、邮箱、电话和地址信息。在提供真实公司资料前，外部联系按钮保持隐藏。",
      formTitle: "货物咨询",
      fields: {
        name: ["姓名", "您的姓名"],
        company: ["公司", "公司名称（选填）"],
        email: ["邮箱", "name@company.com"],
        contact: ["微信或 WhatsApp", "账号或号码（选填）"],
        origin: ["起运地", "中国城市或机场"],
        destination: ["目的地", "城市或机场"],
        message: ["货物与留言", "品名、件数、重量、尺寸、服务方式和时间要求"],
      },
      required: "必填",
      invalidEmail: "请输入有效的邮箱地址。",
      invalidContact: "请输入至少 5 个有效字符，可使用字母、数字、空格、+、-、_ 或 @。",
      submit: "提交演示咨询",
      submitting: "正在检查咨询内容…",
      successTitle: "演示咨询已完成",
      successBody: "没有任何信息被发送或保存。生产环境中，只有安全表单服务确认送达后才会显示此状态。",
      another: "重新填写咨询",
    },
    privacyPage: {
      eyebrow: "隐私政策",
      title: "本原型的隐私说明",
      intro: "此本地演示不会发送、保留或共享表单内容。",
      sections: [
        ["原型数据处理", "联系表单只在浏览器中校验信息。出现成功状态或刷新页面后，填写内容即被丢弃。"],
        ["上线前要求", "正式上线前，公司需要选择安全的表单服务，明确保存期限和访问权限，发布经核实的联系方式与法律信息，并按适用法律取得必要同意。"],
        ["外部服务", "本原型不包含分析工具、广告追踪、聊天组件、地图、社交像素或第三方物流集成。"],
      ],
    },
  },
};
